---
- name: use the paybook  for creation of user
  hosts: 9.181.2.111
  become: true
  sudo: yes
  vars_files: 
    - vault.yml
    - userlist.yml
  tasks:
     - name: ensure ibmsa  group is present
       group:
         name: ibmsa
         state: present
     - name: ensure the user is present in the system
       user:   
         name: "{{item.username}}"
         state: present
         password: "{{aptreasury | password_hash('sha512')}}"
         shell: /bin/bash
         comment: "{{item.comment}}"
         update_password: on_create
         group: ibmsa
       loop: "{{users}}"
       when: item.uid == 'first'
      
     - name: ensure the user is present in the system                    
       user:                                                             
         name: "{{item.username}}"                                       
         state: present                                                  
         password: "{{aptreasury | password_hash('sha512')}}"            
         shell: /bin/bash                                                
         comment: "{{item.comment}}"                                     
         update_password: on_create                                      
         group: ibmsa                                                 
       loop: "{{users}}"                                                 
       when: item.uid == 'second'
