---
- name: create the samba user
  become: true
  hosts: samba
  vars_files: 
    - userlist.yml
    - vault.yml
  vars:
    samba_configuration_dir: /etc/samba
    samba_configuration: "{{samba_configuration_dir}}/smb.conf"
    samba_username_map_file: "{{samba_configuration_dir}}/smbusers"
  tasks:
   - name: ensure the apsettle  group is present
     group:
       name: apsettle
       state: present
   
   - name: ensure the user is present in the system
     user: 
       name: "{{item.username}}"
       state: present
       password: "{{aptreasury | password_hash('sha512')}}"
       shell: /bin/bash
       comment: "{{item.comment}}"
       update_password: on_create
       group: apsettle
     loop: "{{users}}"
     when: inventory_hostname in groups ['samba'] and item.uid = 'first'
   
   - name:create the samba user
     shell: echo -e "gigenericaps2\ngogenericaps2" | smbpasswd -s -a {{item.username}}
     with_items: "{{users}}"
     when: inventory_hostnamein groups ['samba']and item.uid == 'first'

   - name: restart the smb sevrice 
     service:
       name: smb
       state: restarted
     

