---
- name: slack test playbook
  hosts: 9.181.2.111
  tasks:
   - name: notifications  of root password via slack
     slack:
         token: T073LUXEU/B0234N6R78F/1tidTakmoE9EdpPGLg9TiMIj
         msg: '{{inventory_hostname }} root password update is completed successfully'
     delegate_to: localhost
     become: false
